### ISSUE TITLE
consider adding margin below site description

### ISSUE THREAD

**Issue by greglinch** [jessdilla23/final-project23#1]
This is a minor thing, but I'd suggest experimenting (e.g. via the inspector) with adding a little more margin for the `header-menu`. Maybe like 18px or 20px.

Current:

<img width="318" alt="screen shot 2018-11-16 at 5 51 28 pm" src="https://user-images.githubusercontent.com/327783/48651313-54c92700-e9c8-11e8-8526-1b630f0b894a.png">

Possible updated version:

<img width="519" alt="screen shot 2018-11-16 at 5 54 14 pm" src="https://user-images.githubusercontent.com/327783/48651386-aa053880-e9c8-11e8-911b-0c3abf46c221.png">

**Comment by jessdilla23** [comment]
Added!
