### ISSUE TITLE
consider removing border from resume embed

### ISSUE THREAD

**Issue by greglinch** [jessdilla23/final-project23#2]
You can use an HTML attribute called `frameborder` to remove the border:

<img width="1052" alt="screen shot 2018-11-16 at 6 19 20 pm" src="https://user-images.githubusercontent.com/327783/48652186-32d1a380-e9cc-11e8-94a3-fa2861b1f65c.png">

It can make the page look more clean and modern — frame borders are kind of an old-school web thing.

**Comment by jessdilla23** [comment]
Love this idea, thanks!
